<?php

namespace app\models;

use Yii;
use yii\db\Exception;
use yii\db\StaleObjectException;

/**
 * This is the model class for table "dish_ingredient".
 *
 * @property int $id
 * @property int $dish_id
 * @property int $ingredient_id
 * @property string|null $created
 * @property string|null $updated
 */
class DishIngredient extends \yii\db\ActiveRecord
{
    /**
     * @var $customAttDishName string название блюда dish.name по dish_id
     */
    public $customAttDishName;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'dish_ingredient';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['dish_id', 'ingredient_id', 'customAttDishName'], 'required'],
            [['dish_id', 'ingredient_id'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['dish_id', 'ingredient_id'], 'unique', 'targetAttribute' => ['dish_id', 'ingredient_id']],
            [['dish_id'], 'exist', 'skipOnError' => true, 'targetClass' => Dish::className(), 'targetAttribute' => ['dish_id' => 'id']],
            [['ingredient_id'], 'exist', 'skipOnError' => true, 'targetClass' => Ingredient::className(), 'targetAttribute' => ['ingredient_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'dish_id' => 'Dish ID',
            'ingredient_id' => 'Ingredient ID',
            'customAttDishName' => 'Название ингредиента',
            'created' => 'Created',
            'updated' => 'Updated',
        ];
    }

    /**
     * @param bool $runValidation
     * @param null $attributeNames
     * @return bool
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        try {
            // Сначала сохраняем название блюда
            if ( $this->isNewRecord ) {
                $dish = new Dish();
                $dish->name = $this->customAttDishName;
                $dish->insert();
                $this->dish_id = $dish->id;
            } else {
                $dish = Dish::findOne(['id' => $this->dish_id]);
                $dish->name = $this->customAttDishName;
                $dish->update();
            }

        } catch (\Throwable $e) {
            Yii::error($e->getMessage());
            return false;
        }
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}
